apiVersion: v1
kind: Secret
metadata:
  name: gataria-secrets
  namespace: dev
type: Opaque
data:
  MONGO_URL: bW9uZ29kYitzcnY6Ly9hZG1pbmdhdGFyaWE6bWluaGFtYWVAZ2F0YXJpYS40d2tpZnBnLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=